export const SAMPLE = [
  [
    [
      {
        index: 0,
        correctTopIndex: -1,
        correctBottomIndex: 8,
        correctLeftIndex: -1,
        correctRightIndex: 1,
        type: [0, 1, -1, 0],
        position_x: 740,
        position_y: 695,
        locked: false,
      },
      {
        index: 1,
        correctTopIndex: -1,
        correctBottomIndex: 9,
        correctLeftIndex: 0,
        correctRightIndex: 2,
        type: [0, 1, -1, 1],
        position_x: 1640,
        position_y: 595,
        locked: false,
      },
      {
        index: 2,
        correctTopIndex: -1,
        correctBottomIndex: 10,
        correctLeftIndex: 1,
        correctRightIndex: 3,
        type: [0, 1, 1, 1],
        position_x: 640,
        position_y: 395,
        locked: false,
      },
      {
        index: 3,
        correctTopIndex: -1,
        correctBottomIndex: 11,
        correctLeftIndex: 2,
        correctRightIndex: 4,
        type: [0, 1, -1, 1],
        position_x: 1440,
        position_y: 595,
        locked: false,
      },
      {
        index: 4,
        correctTopIndex: -1,
        correctBottomIndex: 12,
        correctLeftIndex: 3,
        correctRightIndex: 5,
        type: [0, 1, 1, 1],
        position_x: 540,
        position_y: 695,
        locked: false,
      },
      {
        index: 5,
        correctTopIndex: -1,
        correctBottomIndex: 13,
        correctLeftIndex: 4,
        correctRightIndex: 6,
        type: [0, -1, 1, 1],
        position_x: 1640,
        position_y: 395,
        locked: false,
      },
      {
        index: 6,
        correctTopIndex: -1,
        correctBottomIndex: 14,
        correctLeftIndex: 5,
        correctRightIndex: 7,
        type: [0, 1, 1, 1],
        position_x: 340,
        position_y: 495,
        locked: false,
      },
      {
        index: 7,
        correctTopIndex: -1,
        correctBottomIndex: 15,
        correctLeftIndex: 6,
        correctRightIndex: -1,
        type: [0, 0, 1, 1],
        position_x: 240,
        position_y: 395,
        locked: false,
      },
    ],
    [
      {
        index: 8,
        correctTopIndex: 0,
        correctBottomIndex: 16,
        correctLeftIndex: -1,
        correctRightIndex: 9,
        type: [1, -1, 1, 0],
        position_x: 440,
        position_y: 595,
        locked: false,
      },
      {
        index: 9,
        correctTopIndex: 1,
        correctBottomIndex: 17,
        correctLeftIndex: 8,
        correctRightIndex: 10,
        type: [1, -1, 1, 1],
        position_x: 340,
        position_y: 695,
        locked: false,
      },
      {
        index: 10,
        correctTopIndex: 2,
        correctBottomIndex: 18,
        correctLeftIndex: 9,
        correctRightIndex: 11,
        type: [1, 1, 1, 1],
        position_x: 1540,
        position_y: 495,
        locked: false,
      },
      {
        index: 11,
        correctTopIndex: 3,
        correctBottomIndex: 19,
        correctLeftIndex: 10,
        correctRightIndex: 12,
        type: [1, -1, 1, 1],
        position_x: 540,
        position_y: 495,
        locked: false,
      },
      {
        index: 12,
        correctTopIndex: 4,
        correctBottomIndex: 20,
        correctLeftIndex: 11,
        correctRightIndex: 13,
        type: [1, 1, 1, 1],
        position_x: 240,
        position_y: 595,
        locked: false,
      },
      {
        index: 13,
        correctTopIndex: 5,
        correctBottomIndex: 21,
        correctLeftIndex: 12,
        correctRightIndex: 14,
        type: [1, -1, 1, 1],
        position_x: 1040,
        position_y: 395,
        locked: false,
      },
      {
        index: 14,
        correctTopIndex: 6,
        correctBottomIndex: 22,
        correctLeftIndex: 13,
        correctRightIndex: 15,
        type: [1, 1, 1, 1],
        position_x: 840,
        position_y: 595,
        locked: false,
      },
      {
        index: 15,
        correctTopIndex: 7,
        correctBottomIndex: 23,
        correctLeftIndex: 14,
        correctRightIndex: -1,
        type: [1, 0, -1, 1],
        position_x: 740,
        position_y: 495,
        locked: false,
      },
    ],
    [
      {
        index: 16,
        correctTopIndex: 8,
        correctBottomIndex: 24,
        correctLeftIndex: -1,
        correctRightIndex: 17,
        type: [1, -1, 1, 0],
        position_x: 1740,
        position_y: 695,
        locked: false,
      },
      {
        index: 17,
        correctTopIndex: 9,
        correctBottomIndex: 25,
        correctLeftIndex: 16,
        correctRightIndex: 18,
        type: [1, 1, 1, 1],
        position_x: 1440,
        position_y: 395,
        locked: false,
      },
      {
        index: 18,
        correctTopIndex: 10,
        correctBottomIndex: 26,
        correctLeftIndex: 17,
        correctRightIndex: 19,
        type: [1, 1, 1, 1],
        position_x: 640,
        position_y: 595,
        locked: false,
      },
      {
        index: 19,
        correctTopIndex: 11,
        correctBottomIndex: 27,
        correctLeftIndex: 18,
        correctRightIndex: 20,
        type: [1, -1, 1, 1],
        position_x: 840,
        position_y: 395,
        locked: false,
      },
      {
        index: 20,
        correctTopIndex: 12,
        correctBottomIndex: 28,
        correctLeftIndex: 19,
        correctRightIndex: 21,
        type: [1, -1, 1, 1],
        position_x: 1540,
        position_y: 695,
        locked: false,
      },
      {
        index: 21,
        correctTopIndex: 13,
        correctBottomIndex: 29,
        correctLeftIndex: 20,
        correctRightIndex: 22,
        type: [1, 1, 1, 1],
        position_x: 1740,
        position_y: 495,
        locked: false,
      },
      {
        index: 22,
        correctTopIndex: 14,
        correctBottomIndex: 30,
        correctLeftIndex: 21,
        correctRightIndex: 23,
        type: [1, 1, -1, 1],
        position_x: 1340,
        position_y: 695,
        locked: false,
      },
      {
        index: 23,
        correctTopIndex: 15,
        correctBottomIndex: 31,
        correctLeftIndex: 22,
        correctRightIndex: -1,
        type: [1, 0, -1, 1],
        position_x: 1240,
        position_y: 595,
        locked: false,
      },
    ],
    [
      {
        index: 24,
        correctTopIndex: 16,
        correctBottomIndex: -1,
        correctLeftIndex: -1,
        correctRightIndex: 25,
        type: [1, 1, 0, 0],
        position_x: 940,
        position_y: 495,
        locked: false,
      },
      {
        index: 25,
        correctTopIndex: 17,
        correctBottomIndex: -1,
        correctLeftIndex: 24,
        correctRightIndex: 26,
        type: [1, 1, 0, 1],
        position_x: 1140,
        position_y: 495,
        locked: false,
      },
      {
        index: 26,
        correctTopIndex: 18,
        correctBottomIndex: -1,
        correctLeftIndex: 25,
        correctRightIndex: 27,
        type: [1, -1, 0, 1],
        position_x: 440,
        position_y: 395,
        locked: false,
      },
      {
        index: 27,
        correctTopIndex: 19,
        correctBottomIndex: -1,
        correctLeftIndex: 26,
        correctRightIndex: 28,
        type: [1, 1, 0, 1],
        position_x: 1040,
        position_y: 595,
        locked: false,
      },
      {
        index: 28,
        correctTopIndex: 20,
        correctBottomIndex: -1,
        correctLeftIndex: 27,
        correctRightIndex: 29,
        type: [1, -1, 0, 1],
        position_x: 1240,
        position_y: 395,
        locked: false,
      },
      {
        index: 29,
        correctTopIndex: 21,
        correctBottomIndex: -1,
        correctLeftIndex: 28,
        correctRightIndex: 30,
        type: [1, 1, 0, 1],
        position_x: 940,
        position_y: 695,
        locked: false,
      },
      {
        index: 30,
        correctTopIndex: 22,
        correctBottomIndex: -1,
        correctLeftIndex: 29,
        correctRightIndex: 31,
        type: [1, 1, 0, 1],
        position_x: 1140,
        position_y: 695,
        locked: false,
      },
      {
        index: 31,
        correctTopIndex: 23,
        correctBottomIndex: -1,
        correctLeftIndex: 30,
        correctRightIndex: -1,
        type: [1, 0, 0, 1],
        position_x: 1340,
        position_y: 495,
        locked: false,
      },
    ],
  ],
  [
    [
      {
        index: 15,
        correctTopIndex: 7,
        correctBottomIndex: 23,
        correctLeftIndex: 14,
        correctRightIndex: -1,
        type: [1, 0, -1, 1],
        position_x: 740,
        position_y: 495,
        locked: false,
      },
      {
        index: 3,
        correctTopIndex: -1,
        correctBottomIndex: 11,
        correctLeftIndex: 2,
        correctRightIndex: 4,
        type: [0, 1, -1, 1],
        position_x: 1440,
        position_y: 595,
        locked: false,
      },
      {
        index: 10,
        correctTopIndex: 2,
        correctBottomIndex: 18,
        correctLeftIndex: 9,
        correctRightIndex: 11,
        type: [1, 1, 1, 1],
        position_x: 1540,
        position_y: 495,
        locked: false,
      },
      {
        index: 8,
        correctTopIndex: 0,
        correctBottomIndex: 16,
        correctLeftIndex: -1,
        correctRightIndex: 9,
        type: [1, -1, 1, 0],
        position_x: 440,
        position_y: 595,
        locked: false,
      },
      {
        index: 30,
        correctTopIndex: 22,
        correctBottomIndex: -1,
        correctLeftIndex: 29,
        correctRightIndex: 31,
        type: [1, 1, 0, 1],
        position_x: 1140,
        position_y: 695,
        locked: false,
      },
      {
        index: 23,
        correctTopIndex: 15,
        correctBottomIndex: 31,
        correctLeftIndex: 22,
        correctRightIndex: -1,
        type: [1, 0, -1, 1],
        position_x: 1240,
        position_y: 595,
        locked: false,
      },
      {
        index: 18,
        correctTopIndex: 10,
        correctBottomIndex: 26,
        correctLeftIndex: 17,
        correctRightIndex: 19,
        type: [1, 1, 1, 1],
        position_x: 640,
        position_y: 595,
        locked: false,
      },
      {
        index: 20,
        correctTopIndex: 12,
        correctBottomIndex: 28,
        correctLeftIndex: 19,
        correctRightIndex: 21,
        type: [1, -1, 1, 1],
        position_x: 1540,
        position_y: 695,
        locked: false,
      },
    ],
    [
      {
        index: 9,
        correctTopIndex: 1,
        correctBottomIndex: 17,
        correctLeftIndex: 8,
        correctRightIndex: 10,
        type: [1, -1, 1, 1],
        position_x: 340,
        position_y: 695,
        locked: false,
      },
      {
        index: 31,
        correctTopIndex: 23,
        correctBottomIndex: -1,
        correctLeftIndex: 30,
        correctRightIndex: -1,
        type: [1, 0, 0, 1],
        position_x: 1340,
        position_y: 495,
        locked: false,
      },
      {
        index: 25,
        correctTopIndex: 17,
        correctBottomIndex: -1,
        correctLeftIndex: 24,
        correctRightIndex: 26,
        type: [1, 1, 0, 1],
        position_x: 1140,
        position_y: 495,
        locked: false,
      },
      {
        index: 29,
        correctTopIndex: 21,
        correctBottomIndex: -1,
        correctLeftIndex: 28,
        correctRightIndex: 30,
        type: [1, 1, 0, 1],
        position_x: 940,
        position_y: 695,
        locked: false,
      },
      {
        index: 22,
        correctTopIndex: 14,
        correctBottomIndex: 30,
        correctLeftIndex: 21,
        correctRightIndex: 23,
        type: [1, 1, -1, 1],
        position_x: 1340,
        position_y: 695,
        locked: false,
      },
      {
        index: 7,
        correctTopIndex: -1,
        correctBottomIndex: 15,
        correctLeftIndex: 6,
        correctRightIndex: -1,
        type: [0, 0, 1, 1],
        position_x: 240,
        position_y: 395,
        locked: false,
      },
      {
        index: 6,
        correctTopIndex: -1,
        correctBottomIndex: 14,
        correctLeftIndex: 5,
        correctRightIndex: 7,
        type: [0, 1, 1, 1],
        position_x: 340,
        position_y: 495,
        locked: false,
      },
      {
        index: 11,
        correctTopIndex: 3,
        correctBottomIndex: 19,
        correctLeftIndex: 10,
        correctRightIndex: 12,
        type: [1, -1, 1, 1],
        position_x: 540,
        position_y: 495,
        locked: false,
      },
    ],
    [
      {
        index: 27,
        correctTopIndex: 19,
        correctBottomIndex: -1,
        correctLeftIndex: 26,
        correctRightIndex: 28,
        type: [1, 1, 0, 1],
        position_x: 1040,
        position_y: 595,
        locked: false,
      },
      {
        index: 16,
        correctTopIndex: 8,
        correctBottomIndex: 24,
        correctLeftIndex: -1,
        correctRightIndex: 17,
        type: [1, -1, 1, 0],
        position_x: 1740,
        position_y: 695,
        locked: false,
      },
      {
        index: 21,
        correctTopIndex: 13,
        correctBottomIndex: 29,
        correctLeftIndex: 20,
        correctRightIndex: 22,
        type: [1, 1, 1, 1],
        position_x: 1740,
        position_y: 495,
        locked: false,
      },
      {
        index: 26,
        correctTopIndex: 18,
        correctBottomIndex: -1,
        correctLeftIndex: 25,
        correctRightIndex: 27,
        type: [1, -1, 0, 1],
        position_x: 440,
        position_y: 395,
        locked: false,
      },
      {
        index: 24,
        correctTopIndex: 16,
        correctBottomIndex: -1,
        correctLeftIndex: -1,
        correctRightIndex: 25,
        type: [1, 1, 0, 0],
        position_x: 940,
        position_y: 495,
        locked: false,
      },
      {
        index: 5,
        correctTopIndex: -1,
        correctBottomIndex: 13,
        correctLeftIndex: 4,
        correctRightIndex: 6,
        type: [0, -1, 1, 1],
        position_x: 1640,
        position_y: 395,
        locked: false,
      },
      {
        index: 4,
        correctTopIndex: -1,
        correctBottomIndex: 12,
        correctLeftIndex: 3,
        correctRightIndex: 5,
        type: [0, 1, 1, 1],
        position_x: 540,
        position_y: 695,
        locked: false,
      },
      {
        index: 0,
        correctTopIndex: -1,
        correctBottomIndex: 8,
        correctLeftIndex: -1,
        correctRightIndex: 1,
        type: [0, 1, -1, 0],
        position_x: 740,
        position_y: 695,
        locked: false,
      },
    ],
    [
      {
        index: 2,
        correctTopIndex: -1,
        correctBottomIndex: 10,
        correctLeftIndex: 1,
        correctRightIndex: 3,
        type: [0, 1, 1, 1],
        position_x: 640,
        position_y: 395,
        locked: false,
      },
      {
        index: 12,
        correctTopIndex: 4,
        correctBottomIndex: 20,
        correctLeftIndex: 11,
        correctRightIndex: 13,
        type: [1, 1, 1, 1],
        position_x: 240,
        position_y: 595,
        locked: false,
      },
      {
        index: 14,
        correctTopIndex: 6,
        correctBottomIndex: 22,
        correctLeftIndex: 13,
        correctRightIndex: 15,
        type: [1, 1, 1, 1],
        position_x: 840,
        position_y: 595,
        locked: false,
      },
      {
        index: 13,
        correctTopIndex: 5,
        correctBottomIndex: 21,
        correctLeftIndex: 12,
        correctRightIndex: 14,
        type: [1, -1, 1, 1],
        position_x: 1040,
        position_y: 395,
        locked: false,
      },
      {
        index: 19,
        correctTopIndex: 11,
        correctBottomIndex: 27,
        correctLeftIndex: 18,
        correctRightIndex: 20,
        type: [1, -1, 1, 1],
        position_x: 840,
        position_y: 395,
        locked: false,
      },
      {
        index: 1,
        correctTopIndex: -1,
        correctBottomIndex: 9,
        correctLeftIndex: 0,
        correctRightIndex: 2,
        type: [0, 1, -1, 1],
        position_x: 1640,
        position_y: 595,
        locked: false,
      },
      {
        index: 17,
        correctTopIndex: 9,
        correctBottomIndex: 25,
        correctLeftIndex: 16,
        correctRightIndex: 18,
        type: [1, 1, 1, 1],
        position_x: 1440,
        position_y: 395,
        locked: false,
      },
      {
        index: 28,
        correctTopIndex: 20,
        correctBottomIndex: -1,
        correctLeftIndex: 27,
        correctRightIndex: 29,
        type: [1, -1, 0, 1],
        position_x: 1240,
        position_y: 395,
        locked: false,
      },
    ],
  ],
];

export const parsePuzzleShapes = (data) => {
  const shapes = [];
  for (let i = 0; i < 2; i += 1) {
    for (let j = 0; j < 4; j += 1) {
      for (let k = 0; k < 8; k += 1) {
        const { type } = data[i][j][k];
        const [topTab, rightTab, bottomTab, leftTab] = type;
        shapes.push({
          topTab,
          rightTab,
          bottomTab,
          leftTab,
        });
      }
    }
  }

  return shapes;
};
